name: windows_app
description: "Salesku App Windows untuk Admin Sales"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  common_components:
    path: ../../packages/common_components

  # RIVERPOD
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # FREEZED
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # MAP & LOCATION
  geolocator: ^14.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  # EXPORT EXCEL
  excel: ^2.0.1
  file_selector: ^0.9.0
  path_provider: ^2.0.14

  # WINDOW SETTINGS
  bitsdojo_window: ^0.1.6

  # OTHERS
  intl: ^0.20.2
  http: ^1.3.0
  fl_chart: ^1.0.0
  file_picker: ^10.1.9
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  googleapis_auth: ^2.0.0
  flutter_screenutil: ^5.9.3
  month_picker_dialog: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.3

  # RIVERPOD
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

  # FREEZED
  build_runner: ^2.4.6
  freezed: ^2.5.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    # MADURA
    - assets/bangkalan.geojson
    - assets/sampang.geojson
    - assets/pamekasan.geojson
    - assets/sumenep.geojson

    - assets/tuban.geojson
    - assets/lamongan.geojson
    - assets/gresik.geojson

    - assets/surabaya_kota.geojson
    - assets/sidoarjo.geojson
    
    - assets/mojokerto.geojson
    - assets/mojokerto_kota.geojson
    - assets/malang.geojson
    - assets/malang_kota.geojson

    - assets/pasuruan.geojson
    - assets/pasuruan_kota.geojson
    - assets/probolinggo.geojson
    - assets/probolinggo_kota.geojson
    - .env
