name: common_components
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # FREEZED
  fpdart: ^1.1.1

  # ENCRYPTION
  encrypt: ^5.0.3
  crypto: ^3.0.6

  # OTHERS
  http: ^1.3.0
  mime: ^2.0.0
  intl: ^0.20.2
  http_parser: ^4.0.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0