include: package:flutter_lints/flutter.yaml

analyzer:
  # plugins:
  #   - custom_lint

  errors:
    depend_on_referenced_packages: ignore
    invalid_annotation_target: ignore
    non_constant_identifier_names: ignore
    prefer_interpolation_to_compose_strings: ignore
    use_build_context_synchronously: ignore
    file_names: ignore

custom_lint:
  enable_all_rules: true

linter:
  rules:
    avoid_dynamic_calls: false
    avoid_print: true # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true
    prefer_const_constructors: true
    require_trailing_commas: true
    always_declare_return_types: true
    no_leading_underscores_for_local_identifiers: false
    library_private_types_in_public_api: false

dart_code_metrics:
  extends:
    - recommended
    
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
