name: android_app
description: "Salesku App Android untuk Sales Lapangan"
publish_to: "none"
version: 0.1.0+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  common_components:
    path: ../../packages/common_components

  # RIVERPOD
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # FREEZED
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # MAP & LOCATION
  geolocator: ^14.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  # IMAGE PICKER & WATERMARK
  image: ^4.5.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0

  # FONT
  google_fonts: ^6.2.1

  # OTHERS
  intl: ^0.20.2
  http: ^1.3.0
  encrypt: ^5.0.3
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.3

  # RIVERPOD
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

  # FREEZED
  build_runner: ^2.4.6
  freezed: ^2.5.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - .env
